### ISSUE TITLE
NEON Management Tools menu is only displayed for SuperAdmins (other Admins/Editors can't see it)

### ISSUE THREAD

**Issue by arbolitoloco** [BioKIC/NEON-Biorepository#106]
Commit 4eab15d15a1baa39803debeffbdf119d54526062 adds the conditional display of the management tools menu, but just for SuperAdmins. 
It should be fixed to be displayed for all kinds of Admins and Editors in the Collection level.
The way it is right now, forces a large number of occasional users to be SuperAdmins, which I think is a security risk.

**Comment by arbolitoloco** [comment]
This is not going to be fixed.

**Comment by kyule** [comment]
Was fixed 9/24/21! NEON tools now visible for anyone made an editor or admin of any of the portal collections. From Ed: "I've adjusted the permission handling within the NEON menus and tools. Previous, only SuperAdmin had access to the NEON specific tools. Now, if you make someone an editor or admin for any collection (permission management tool is available within collections management menu), they will also have access to the NEON management menus, sample checking tools, shipment search tools, etc, but not the IGSN harvesting tools, batch occurrence harvester, and other tools that only admin should do."
