### ISSUE TITLE
Indicate whether species are available in NEON collections in Research Checklists

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#113]
In the Research checklists pages, we should make it clear whether a species has been collected by NEON. 

Potential solution: Change the color of taxon names found in the NEON collections.

E.g. Make "Neotoma albigula" a different color, but leave "Zenaida macroura" as is.
<img width="967" alt="image" src="https://user-images.githubusercontent.com/4763928/75734768-18e9cc00-5cb6-11ea-87b9-196d2db1b7a2.png">

https://biorepo.neonscience.org/portal/checklists/checklist.php?clid=45&pid=1

Related to issue #40

**Comment by arbolitoloco** [comment]
Working on this

**Comment by arbolitoloco** [comment]
See [this invertebrate checklist](https://biokic4.rc.asu.edu/biorepo/checklists/checklist.php?clid=103&pid=6) for a working example
