### ISSUE TITLE
Page Pointing to all Collections Profile Pages

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#120]
**Is your feature request related to a problem? Please describe.**
When the new search form is implemented, it will not be as clear to find the Collection's profile pages that contain a lot of useful information

**Describe the solution you'd like**
An easily accessible single page should be made available that links to those pages for all of the collections.

**Comment by arbolitoloco** [comment]
It seems like my "Collection Profiles" experimental app solves this? Will reference this issue once it is deployed.
