### ISSUE TITLE
change "USA" to "United States" in Country field

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#125]
The following collections contain samples/specimens where the country is listed as "USA". Please change "USA" to "United States" in these collections:

Aquatic Microalgae Collection (Chemical Preservation)(NEON:AMIC-CP)
Terrestrial Plant Collection (Herbarium Vouchers)(NEON-TPLC-HV
Herptile Voucher Collection (Small Mammal Sampling Bycatch)(NEON:HEVC-SMMB)

Priority: Low

**Comment by mandrewj** [comment]
Updated all records in symbneaon.omoccurrences with country = 'USA' to country = 'United States'

372 records updated.
