### ISSUE TITLE
Samples with missing State/Province

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#127]
Collections that contain samples with missing State/Province:
Aquatic Plant, Bryophyte, and Lichen Collection (Herbarium Vouchers [Clip Harvests])
Aquatic Plant, Bryophyte, and Lichen Collection (Herbarium Vouchers [Clip Harvests])(NEON-APLC-HVCH)

Please add state location information.

Priority: Medium

**Comment by kyule** [comment]
Some code update must have fixed this as no NEON-APLC specimens are lacking stateProvince anymore
