### ISSUE TITLE
Occurrence harvesting issues for all samples in Terrestrial Plant Collection (Belowground Biomass [Megapit])

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#128]
Occurrence Harvesting Error: locality data failed to populate
Terrestrial Plant Collection (Belowground Biomass [Megapit])(NEON-TPLC-BBM)

Priority: Medium

**Comment by kyule** [comment]
Given dated provided by Katie Levan through ServiceNow, we now have locality data for all samples except MAME samples (mpr_002 shipment).  Closing this issue, we can track the remaining issues in #179
