### ISSUE TITLE
Copy URL to clipboard does not work for Map Search

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#129]
The "Copy  URL to clipboard" button only copies  the Map Search landing page. 

To replicate,  conduct any Map Search, click the "Copy  URL to clipboard" button, attempt  to  paste the URL into  the browser, land on the basic Map  Search page with no results.

**Comment by arbolitoloco** [comment]
Works on Chrome in a Windows 10 machine

**Comment by kyule** [comment]
And on Firefox on Mac
