### ISSUE TITLE
Cannot retrieve uploaded manifests from portal

### ISSUE THREAD

**Issue by azhar-h** [BioKIC/NEON-Biorepository#136]
In Manifest View, I cannot download previously submitted manifest CSV files.

**To Reproduce**
1. In biorepo portal, go to Home >> NEON Biorepository Tools >> Manifest Search
2. Scroll down the page and click on any link in Shipment Listing 
3. Click Import file name link
4. See error - screencap attached

 - Chrome
 - Version 83.0.4103.97 (64-bit)

<img width="952" alt="Screen Shot 2020-08-06 at 4 55 32 PM" src="https://user-images.githubusercontent.com/66031680/89594652-490a3d80-d807-11ea-98bc-701c54582d42.png">

**Comment by arbolitoloco** [comment]
It seems like this is happening since last server migration. Ed is looking into retrieving the missing manifests.
