### ISSUE TITLE
Collector information not displaying in occurrence records for herbarium vouchers (Biorepo or Service Now?)

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#138]
For herbarium vouchers (sample class: div_voucher_in.voucherSampleID.pla), the Collector field is blank in the Biorepo portal but is included on the voucher labels. Is Collector info available in the NEON API? Can we pull it in? This may be an issue that needs to be reported to Service Now (just let me know and I can submit a request).

**Example** For sample with barcode A00000075116, compare occurrence record with herbarium sheet label:
Occurrence record: 
![image](https://user-images.githubusercontent.com/55719283/89680220-65f64d80-d8a7-11ea-8110-b20c3936d8e1.png)

Herbarium label:
![herbarium label A00000075116](https://user-images.githubusercontent.com/55719283/89680148-3e9f8080-d8a7-11ea-8bbe-89110ccadaa7.jpg)

**Comment by kyule** [comment]
Collector now available to us in NEON API, should not be a problem moving forward.
