### ISSUE TITLE
Pervasive Occurrence Harvesting Problems

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#145]
**Describe the bug**
When harvesting occurrences from the manifest module, about 50% or more of the time the harvester will report the error "ERROR: NEON API failed searching by sampleID and sampleClass".  However, by re-running the harvest occurrences task, if will eventually harvest all of the occurrences.  In general, a manifest of 100 samples will require an iterative process of 6-7 harvests where only the samples lacking occurrences are attempted to re-harvest.  Each iteration about half of the samples will be properly harvested while the other half give the error over and over again.

Additionally, there are occasionally partial harvests but the locality will not populate from the API.  By reharvesting and replacing values that error will eventually be fixed, too.

**To Reproduce**
1. Go to manifest module
2. harvest samples (that have been checked in)
3. see errors.

**Full URL**
https://biorepo.neonscience.org/portal/neon/shipment/manifestsearch.php - note that I have done the iterative approach on about 15 manifests spread across 5 days.  None have been left incomplete.

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome and safari on imac

**Comment by arbolitoloco** [comment]
Turns out NEON changed the amount of data packages sent out to the public API. Please hold tight while we secure a special API key and can resume normal data harvesting.
