### ISSUE TITLE
Change USA to United States in Country field for Aquatic Macroalgae Collection (Chemical Preservation [Clip Harvests]) (NEON-AMAC-CPCH)

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#149]
Both USA and United States are used in the Country field for Aquatic Macroalgae Collection (Chemical Preservation [Clip Harvests]). Please change all "USA" to "United States".

**Comment by mandrewj** [comment]
Updated all omoccurrences records with county 'USA' to 'United States'
