### ISSUE TITLE
State not displaying for six records in NEON-APLC-HVCH

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#152]
State field is blank for six records in Aquatic Plant, Bryophyte, Lichen, and Macroalgae Collection (Herbarium Vouchers [Clip Harvests])(NEON-APLC-HVCH). If this is no longer a code issue, let me know and I will go in and manually add the state name.

![image](https://user-images.githubusercontent.com/55719283/95895331-5da30e80-0d3f-11eb-956d-a166d783158e.png)

**Comment by kyule** [comment]
Since it's so specific, it didn't seem like it'd be a widespread code problem, so I updated these records manually
