### ISSUE TITLE
Material samples module requests: materialSample output file should include occurrence data from the parent sample

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#16]
At a minimum, the materialSample output file should include the parent sample catalog number (suggest parentCatalogNumber) and scientificName. Is it possible to add those fields to the materialSample output file? From the viewpoint of researchers interested in using tissue samples from small mammal vouchers for genetic, virus, etc., research, **combining the occurrence data output WITH the materialSample output into a single materialSample file would be ideal** and make it very easy for searching and requesting tissue samples. Right now, in the materialSample output file, one cannot determine what the parent voucher is (even if one has the occurrence record file; there is no way to link the two files).

**Comment by kyule** [comment]
@lsteger I'm going to close this one. It would make the downloads easier to interpret for many users, but it isn't getting buy in from developers. Likely because the change would not be trivial and the current format is consistent across all of the data extensions in downloads.
