### ISSUE TITLE
Create multi-collection loan from user interface

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#162]
Many (most?) loans involve samples from multiple sampleClasses (= collections).

Collection managers need to be able to create a single loan within the portal and add specimens from other collections.

To my knowledge, this is only doable in the database currently?

**Comment by kyule** [comment]
Does this also fix https://github.com/BioKIC/NEON-Biorepository-Data-Docs/issues/86

**Comment by mandrewj** [comment]
We need to talk about this today at our meeting.

We can now add samples from across collections to the same loan - so that is super helpful.  However, I still think that trying to manage loans split across, say, 20+ collection profiles in the portal will likely lead to things falling through the cracks
