### ISSUE TITLE
Limited intermittent harvesting issues - NEON API issues?

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#166]
**Describe the bug**
Related to: https://github.com/BioKIC/NEON-Biorepository/issues/145

The new NEON API token has fixed the pervasive harvesting issues.  However, it still happens intermittently about 1% of the time as opposed to 50-70% of the time.  By selecting all samples with harvesting problems and immediately re-harvesting the data are propagated into symbiota from the NEON API, so this does not seem to be a data avaiability issue but rather some sort of throttling or API response error resulting in failed record harvesting.

**To Reproduce**
Harvest a batch of new samples.  Then attempt to re-harvest all those with errors.

For the 149 samples below, there was one failed sampleID/sampleClass call and one failed locality harvest.  Second attempt immediately after the first harvest run (~2 minutes later) both of those samples were fully harvested correctly.

https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=1791

**Comment by mandrewj** [comment]
For a second data point:
https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentpk=1744

530 samples, 7 had errors (2 fails for sampleID+sampleClass, 5 locality errors) - all successfully harvested from immediate retry.

**Comment by arbolitoloco** [comment]
We were told there are no API restrictions applied to our account, so it was suggested that this might be happening due to others posting requests to the NEON API concomitantly, thus not something we can fix. We'll have to be patient and perform multiple harvesting procedures to get the full data.
