### ISSUE TITLE
Locality inconsistencies in Aquatic Microalgae Collection (Chemical Preservation)(NEON:AMIC-CP)

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#189]
Collection: Aquatic Microalgae Collection (Chemical Preservation)(NEON:AMIC-CP)

Issue: For many records, the locality info is not complete and lacks the Domain and site info. For example, it should be in a format like this: "Domain 03, Barco Lake Site, Riparian, 06 - Riparian Point,, 29.675982 -82.008414", but many records only have latitude and longitude.

![image](https://user-images.githubusercontent.com/55719283/97746197-2a82ae00-1aa7-11eb-8a5b-ef4c8398b6bb.png)

**Comment by arbolitoloco** [comment]
Same issue as #190

**Comment by kyule** [comment]
Closing this issue as it is confirmed that it will be fixed upon re-harvesting.
