### ISSUE TITLE
Add Editor button on Checklist Administration page is too large

### ISSUE THREAD

**Issue by Egariepy2416** [BioKIC/NEON-Biorepository#19]
https://biorepo.neonscience.org/portal/checklists/checklistadmin.php?clid=33&pid=2

**Comment by Egariepy2416** [comment]
"Sample Search", "Map Search", and "Checklists" buttons on the front page under the map are also too large.

**Comment by Egariepy2416** [comment]
Both the "Search" and "Verify Protections" buttons are too large on the Protected Species Page. Also the "Verify Protections" text is way too small on the button.

https://biorepo.neonscience.org/portal/collections/misc/protectedspecies.php

**Comment by Egariepy2416** [comment]
"Search" button on Species with Images page is too large

https://biorepo.neonscience.org/portal/imagelib/index.php

**Comment by Egariepy2416** [comment]
"Build Checklist" button on Dynamic Map page is too large 

https://biorepo.neonscience.org/portal/checklists/dynamicmap.php?interface=checklist

**Comment by Egariepy2416** [comment]
"Search" button on Users page is too large

https://biorepo.neonscience.org/portal/profile/usermanagement.php

**Comment by Egariepy2416** [comment]
"Populate GUIDS" Button on GUID Maintenance Control Panel is too large 

 https://biorepo.neonscience.org/portal/collections/admin/guidmapper.php

**Comment by Egariepy2416** [comment]
"Build Wordstat Tables" Button too large

https://biorepo.neonscience.org/portal/collections/specprocessor/salix/salixhandler.php

**Comment by Egariepy2416** [comment]
"Edit taxon" button is too large

https://biorepo.neonscience.org/portal/taxa/profile/tpeditor.php?tabindex=1

**Comment by Egariepy2416** [comment]
"Submit Edits" and "Delete Project" buttons are too large

https://biorepo.neonscience.org/portal/projects/index.php?pid=1&emode=1

**Comment by Egariepy2416** [comment]
These pages have buttons that are too large:
https://biorepo.neonscience.org/portal/taxa/profile/tpeditor.php?taxon=
https://biorepo.neonscience.org/portal/taxa/profile/tpeditor.php?taxon=&tabindex=4
https://biorepo.neonscience.org/portal/taxa/profile/tpeditor.php?taxon=&tabindex=1
https://biorepo.neonscience.org/portal/taxa/profile/tpeditor.php?taxon=&category=imageadd&tabindex=3
https://biorepo.neonscience.org/portal/taxa/taxonomy/taxonomydisplay.php
https://biorepo.neonscience.org/portal/taxa/taxonomy/taxonomyloader.php
https://biorepo.neonscience.org/portal/taxa/taxonomy/batchloader.php
https://biorepo.neonscience.org/portal/taxa/profile/eolmapper.php

**Comment by arbolitoloco** [comment]
Closed by https://github.com/BioKIC/NEON-Biorepository/commit/92d3c85e861c5511c3f6d547f81c13f21f1ded08
