### ISSUE TITLE
Current Occurrence Harvester Errors page contains OPAL, Samples Not Accepted for Analysis, and Samples Not Received

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#205]
Current Occurrence Harvester Errors page is counting OPAL, Samples Not Accepted for Analysis, and Samples Not Received, which it should not as those samples should not be harvested. So, the total number of samples with errors is not correct and slightly inflated. OPAL samples, Samples Not Accepted for Analysis, and Samples Not Received should be removed from that page and totals.

Current Occurrence Harvester Errors page: https://biorepo.neonscience.org/portal/neon/shipment/harvesterreports.php

Example: 
OPAL samples being included in harvesting error summary totals:  https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=1799&sampleFilter=harvestingError

OPAL and Samples Not Accepted for Analysis being counted in harvesting error summary totals: https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=426&sampleFilter=harvestingError

Samples Not Received being counted in summary totals:
https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=93&sampleFilter=harvestingError

**Comment by arbolitoloco** [comment]
Fixed by 3e989416
