### ISSUE TITLE
Loan Module fails to add some samples with multiple otherCatalogNumbers

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#214]
The Loan Module will not always link samples using the 'link with barcode' tool.

So far, all barcodes have worked, but if you type in a NEON sampleID it only works for samples without a barcode.  When you type in a sampleID for an occurrence that has a barcode as well, it gives an error saying "more than one specimen located with same catalog number" - however when you search that is not true.  It seems that the double otherCatalogNumbers is in fact triggering that warning and stopping the linkage of that sample.

As an example:
BART_025.20180516.IB.01

<img width="1237" alt="Screen Shot 2021-03-23 at 8 21 00 AM" src="https://user-images.githubusercontent.com/6679254/112172026-93cba080-8bb1-11eb-9efa-feb36f8fdd6d.png">

But by scanning the barcode it links just fine.

Also if you try to use the batch link interface it still gives the warning (in this case the sample was already linked via the barcode, hence the second warning)

<img width="444" alt="Screen Shot 2021-03-23 at 8 23 43 AM" src="https://user-images.githubusercontent.com/6679254/112172128-ad6ce800-8bb1-11eb-84a7-0fa380168724.png">

**Comment by mandrewj** [comment]
To clarify above - if you use the "link with barcode" tool and type in the neon sampleID on any sample without a barcode it still works - and the search appears case insensitive, so the lower case letters above are not responsible for the failure - and I have tested the case sensitivity both ways, just didn't take multiple screenshots.

**Comment by kyule** [comment]
@mandrewj Is this still an issue? I wasn't able to replicate it in a test loan with the example sampleID you gave

**Comment by mandrewj** [comment]
I think this was resolved with the various identifier updates, will close for now since I haven't encountered this issue again in the several thousand samples loaned since.
