### ISSUE TITLE
Manifest viewer needs slight table adjustment

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#219]
**Describe the bug**
The manifest viewer needs to have the 'Check-in' column widened slightly.  That column seems to be hard-coded for width and no matter what size my window is, any record that is checked in has a line-break which widens the entire row.

The pencil icon next to the time stamp is pushed down to the next line

**To Reproduce**
Go to: https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=1932&x=7&y=5 or any other shipment, look at the table

**Screenshots**
<img width="1169" alt="Screen Shot 2021-04-09 at 12 12 02 PM" src="https://user-images.githubusercontent.com/6679254/114251872-77708780-9957-11eb-87f3-6984ff1328d9.png">

**Desktop (please complete the following information):**
 - Chrome one a mac

**Comment by mandrewj** [comment]
Whoops, forgot to mention that the occid also breaks the line.  Before the new styles, those all fit on a single line and didn't expand the table.  This makes the lines uneven for samples checked in and those that aren't and is not conducive to checking in large shipments.

**Comment by arbolitoloco** [comment]
This table needs to be responsive, so that icons don't collapse in an awkard way.
