### ISSUE TITLE
Harvested collectedBy data are only orcids - not names

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#24]
ORCIDs are being harvested presumably from the API for new samples.  These are not flagged as ORCIDs in the system (no hyperlink is available) and no names are presented.

see:
https://biorepo.neonscience.org/portal/collections/individual/index.php?occid=910692

2 actions should take place with this:

1 - the harvester should code these as orcids so that the portal identifies them as such and creates a hyperlink, i.e. (ORCID 0000-0001-5623-6512) - an unnamed string is not a good identifier.

2 - We want the collector names to show up in addition to the ORCIDs, I know this is linked/part of another issue where we need to get agent data from NEON - though we should be able to pull first and last name from the ORCID api: https://info.orcid.org/documentation/api-tutorials/api-tutorial-searching-the-orcid-registry/

**Comment by kyule** [comment]
I believe that this is how it is already being done when the person can be found in the NEONPersonnel table and ORCID is included in their record. Therefore, it is not being "optimally" harvested either when the samples are old and it was before NEON was implementing ORCIDs or when the person is "newer" than the last update to that table. We could in the future implement a way to pull the names from the ORCID As at least a stopgap we should  get an updated list of personnel from NEON. I will ask for a new list.

**Comment by kyule** [comment]
Here is a new list to upload. This one should entirely replace the old list, as it was not just out of date but also had numerous errors. @sunray1 Assigning you since I do not have permissions to make deletions in the database. https://drive.google.com/file/d/1JDFqjAGTeBoZ1yW5UEEIsgMeD8j6R40y/view?usp=sharing
