### ISSUE TITLE
Harvesting errors D0620210804133251416 

### ISSUE THREAD

**Issue by azhar-h** [BioKIC/NEON-Biorepository#242]
[D0620210804133251416](https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=2178)

Thanks,
Azhar
![2178 Harvesting errors 02Sep2021](https://user-images.githubusercontent.com/66031680/131893986-30e30a12-1c2d-4e97-a14e-2e1409fc9057.png)

**Comment by kyule** [comment]
these are being reported in the occurrence harvester and we will attempt reharvesting later
