### ISSUE TITLE
Harvesting error D0920210517112705501

### ISSUE THREAD

**Issue by azhar-h** [BioKIC/NEON-Biorepository#244]
![Harvesting errors D0920210517112705501 07Sep2021](https://user-images.githubusercontent.com/66031680/132395627-1dd2d55f-e1bc-44ef-acac-d910a73f839d.png)

Occurrence Harvesting Error: NEON API failed to return sample data
[D0920210517112705501](https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=2066)

Please let me know if these types of errors are being tracked elsewhere and do not to be reported as GitHub issues.

Thanks,
Azhar

**Comment by kyule** [comment]
@azhar-h Yes, these issues are being tracked in the occurrence harvester report page. My previous data responsibilities document that outlined the need to create github issues for harvesting errors was very unclear / has now been refined: only 'novel' issues need to be reported. For example, issues that you were reporting a couple weeks back with the strange error messages that were preventing harvesting and weren't being recorded in the manifest were very good to report (https://github.com/BioKIC/NEON-Biorepository-Data-Docs/issues/107). These more run-of-the-mill ones are fine to ignore at the point of harvesting as others will be going back to look at them periodically.
