### ISSUE TITLE
Request: Add the shipmentID field to CSV export of manifest search results

### ISSUE THREAD

**Issue by azhar-h** [BioKIC/NEON-Biorepository#247]
We are checking in thousands of legacy samples that are often disassociated from their original shipments. When searching the portal for checked-in samples by day, the search result CSV file does not list the shipmentID for each sample. Can this field be added to the search result file?

Having this information associated with the sampleIDs will allow us to more easily go back and review these older manifests for check-in completeness.

Thanks,
Azhar

**Comment by kyule** [comment]
Fixed by Ed 8/11/22
