### ISSUE TITLE
Request: Add a batch sample search option to Manifest Search shipment filter

### ISSUE THREAD

**Issue by azhar-h** [BioKIC/NEON-Biorepository#253]
In Manifest View, a biorepo-side user can search the portal for a single sampleCode, sampleID, shipmentID, domainID etc. 

Request to add a batch search option to allow search for multiple sampleCodes or sampleIDs. This would allow search results from different shipment manifests, domains, collection years etc. Hoping we could include these fields from the respective manifests as part of the batch search results.

Thanks,
Azhar

**Comment by kyule** [comment]
If this only a rare occurrence, can get download from backend database and do some table joining potentially for whatever info is needed.
