### ISSUE TITLE
Beetle sample data unable to be harvested across sample classes

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#256]
**Describe the bug**
Harvester is unable to harvest locality data for beetle samples.  I think this is due to the obfuscated sampleIDs in the portal.  The sample now "harvests" but no data are pulled from the API and only data from the manifest is being put into the records.

The recent change to obscuring beetle sampleIDs initially caused the samples to not harvest, but an update to the code now appears to say it partially harvests even though no other data are pulled into the portal. This is happening across all sample types (invert bycatch, herp bycatch, and beetle tubes) and you can see examples in the two linked manifests.

**To Reproduce**
https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=2284
https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=2262

**Comment by kyule** [comment]
Checked a couple of occurrences and see full data.
