### ISSUE TITLE
Manifest Search page modifications - radio buttons to check boxes

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#257]
With the ever growing number of manifests in our system we need to be able to perform more detailed searches to pull up manifests.  A major issue currently is the use of radio buttons where we can only select one option when in reality we often need to search for multiple options at the same time.

The page in question is:
https://biorepo.neonscience.org/portal/neon/shipment/manifestsearch.php

The first modification could be changing radio buttons to check boxes to allow any/all to be selected simultaneously.

<img width="1546" alt="Screen Shot 2021-12-09 at 1 24 47 PM" src="https://user-images.githubusercontent.com/6679254/145470370-b3f363f2-e03b-4b4b-ab4e-4598d36932d4.png">

A table view or other metadata displayed instead of a list of manifests may also be good in the future.

Finally - we may not want to display the full list of manifests when newly opening the page - as we get more it will only take longer and longer to load.

**Comment by arbolitoloco** [comment]
@mandrewj Can you please describe one combined search that you would like to see with the expected results so I can debug the modification? Thank you.

**Comment by mandrewj** [comment]
I would like to be able to search by any combination of those current radio button criteria.

Examples would be:
1. - Shipments checked in + occurrences not harvested
This would return all shipments checked in that have at least some occurrences not harvested, likely would include a sample class filter as well.

2. - shipments checked in + Receipt not submitted + Samples checked in
This would return matching manifests which could be checked and have receipts submitted.

3. - Shipments checked in + Receipt not submitted + samples not checked in
4. This would return the matching manifests so that those samples could be investigated and the shipments finalized and receipts submitted
