### ISSUE TITLE
Add collector names to mammal voucher collections (for new vouchers received)

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#258]
Please add the collector name (and ORCID) to the collector field for the mammal voucher collection collid=28. We have received a bunch of new vouchers for 2021 and they lack this information. I believe that last time we received a .csv file from NEON with this information since it currently is not harvestable from the NEON API. This is a somewhat urgent request. Thank you!

**Comment by lsteger** [comment]
Some 2021 voucher do have the ORCID  in the collector field, would it be possible to add the collector's name to that field, too?

**Comment by kyule** [comment]
Many of these vouchers still have orcids instead of names. We likely need to implement a method for obtaining names from the orcid api during harvesting.

**Comment by kyule** [comment]
Closing this issue as it seems much of this collection does now have collector names and the broader effort to connect names to the orcids or emails we receive is addressed elsewhere.
