### ISSUE TITLE
Add NEON vertebrate voucher collections to CSVcol

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#262]
**Is your feature request related to a problem? Please describe.**
NEON collections could get more visibility by being added to other vert portals

**Describe the solution you'd like**
The following collections should be added to the CSVcol portal.

FISC-V
HEVC-GBAP
HEVC-GBTS
HEVC-SMMB
MAMC-VGBA (no samples yet)
MAMC-VGBT
MAMC-VOS
MAMC-VSS

**Comment by mandrewj** [comment]
Added combined collections to the CSVcoll portal and created import profiles.

Herptiles:
https://csvcoll.org/portal/collections/misc/collprofiles.php?collid=1070&emode=1

Mammals:
https://csvcoll.org/portal/collections/misc/collprofiles.php?collid=1074

Fish:
https://csvcoll.org/portal/collections/misc/collprofiles.php?collid=1075

Two outstanding issues related to this are:

1 - Taxon codes in place of scinames are propagated from the biorepo portal, see this and linked issues https://github.com/BioKIC/NEON-Biorepository-Data-Docs/issues/102

2 - The mammals and herptiles imported correctly but the fish break the import tool at cleaning taxonomy.

The upload profile is set up the same as the others and it gets to the point where you can map fields, but then when uploading occurrences to the temp tables it breaks I cannot figure out why.  Try importing from the saved profile here to reporoduce:

https://csvcoll.org/portal/collections/admin/specuploadmanagement.php?collid=1075
<img width="1695" alt="Screen Shot 2022-01-24 at 10 15 44 AM" src="https://user-images.githubusercontent.com/6679254/150831722-fd5fc2e6-015b-4b35-9c2e-b7c1568bb5c3.png">

**Comment by mandrewj** [comment]
August commit fixed the issue. All NEON vert collections were just updated on CSVcoll today. 

Note to @lsteger and @kyule - someone on our team might want to (or be assigned to) make a mechanism or calendar reminder to update these collections periodically. There is a saved upload profile but someone has to trigger it on the 3 CSV collections. 

This particular issue should be closed
