### ISSUE TITLE
Remove NEON UUID from label templates (Print Specimen Labels tool)

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#264]
For mammal (wet, skull) and herbarium packet labels, please remove NEON sampleUUIDs from the bottom of all label templates. The NEON UUIDs do not need to appear on labels. Thank you!

![image](https://user-images.githubusercontent.com/55719283/151048414-ee831e78-d2a6-419a-91f8-a32b22ce56f1.png)

**Comment by arbolitoloco** [comment]
Done in production as of today
