### ISSUE TITLE
Remove ORCID ID after collector's name in label templates (Print Specimen Label tool)

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#265]
For mammal (wet, skull) and herbarium packet labels, please remove, if possible, the ORCID ID that is in parentheses after the collector's name. The ORCID ID takes up too much room on the label. Thank you.
![image](https://user-images.githubusercontent.com/55719283/151048855-808d5d0a-69b3-4abc-98aa-32c5c7236f68.png)

**Comment by arbolitoloco** [comment]
Done and in production today.
