### ISSUE TITLE
Add collector name to collector field in collid=28 (Mammal Collection (Vouchers [Standard Sampling]) (NEON-MAMC-VSS)) 

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#266]
A bunch of new mammal vouchers were added to Mammal Collection (Vouchers [Standard Sampling]) (NEON-MAMC-VSS) (collid=28), Laura RP would you be able to add the full name of the collector for vouchers that only have the ORCID ID listed (from the table that NEON provided)? Thank you.

![image](https://user-images.githubusercontent.com/55719283/151049314-20e91788-40b9-4521-945f-2e25c3d31a1b.png)

**Comment by kyule** [comment]
Related to issue #258

**Comment by kyule** [comment]
Spot checked these and I am currently seeing collector names and orcids. The issue of connecting the orcids/emails to the names is a larger one being addressed elsewhere so I'm going to close this issue.
