### ISSUE TITLE
Request for new label profile: NEON Herbarium Label

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#267]
**Is your feature request related to a problem? Please describe.**
NEON terrestrial plant vouchers are sent to us with labels, but occasionally the labels are either missing, damaged, or only one label is included for duplicate material. It would be incredibly useful to have the ability to print new labels for vouchers mounted on herbarium sheets.

**Describe the solution you'd like**
Labels for herbarium sheets should contain the same information (and general layout) as the existing herbarium packet labels. However, sheet labels should be 3 inches (height) x 5 inches (width), maximally. Two labels could be printed on a single sheet. 

Hoping that we can match this example, which shows the current format used by NEON domain staff:
![IMG_20220125_123736194](https://user-images.githubusercontent.com/55719283/151055214-ca4e114b-1835-4cb2-b1c6-1012b05790d8.jpg)

**Comment by arbolitoloco** [comment]
Label format developed, tested and adjusted. Ready for use.
