### ISSUE TITLE
Material samples module requests: add new fields preservationTemperature and preparationType, modify dropdown lists

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#273]
Couple of requests for the material samples module:
1. Please add a new field: **preservationTemperature**. The dropdown list of options for this field should contain the following:
4C
-20C
-80C
LN2
RT

note: do not include degree symbol as it does not translate well in the data download file

2. For **preservationType**, the dropdown list should include: 
dried
ethanol 70%
ethanol 75%
ethanol 80%
ethanol 95%
microscope slide
silica
snap/flash freeze
no preservative

3. Can we also add **preparationType** to record the specific tissues (muscle, liver, heart)? This should be a text field; no dropdown list.

Priority: high

**Comment by lsteger** [comment]
Updating this request and requesting a meeting to discuss before changes are made. 
Instead of having preservationType and preparationType, now recommending just adding more options to preservationType (and not adding a new field called preparationType)
Recommended dropdown list:
ethanol, 70
ethanol, 75
ethanol, 80
ethanol, 95
frozen (-20C)
frozen (-80C)
frozen (-196C)
ethanol, 95, stored frozen (-80C)
ethanol, 95, stored frozen (-196C)

formalin
formalin-fixed, stored in ethanol, 70
formalin-fixed, paraffin-embedded
slide


pinned
glycerin
Nobuto strip

frozen, flash, stored frozen (-80C)
frozen, flash, stored frozen (-196C)


and remove "Liquid Nitrogen" from list

**Comment by arbolitoloco** [comment]
Updated in database as of 2022-08-23.
