### ISSUE TITLE
Map legends do not print taxon names that are in the thesaurus

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#274]
When mapping several species, I found that the legend in the map view of search results will not show the taxon names.  See screenshot below:

<img width="1493" alt="Screen Shot 2022-03-01 at 12 43 41 PM" src="https://user-images.githubusercontent.com/6679254/156237535-fde9b295-06e2-40bf-9eeb-05a7e2ca26d5.png">
This search was for the genus 'Pasimachus' which returns many records for 8 distinct species, all of which are in our taxonomic thesaurus: https://biorepo.neonscience.org/portal/collections/list.php?db=39&includeothercatnum=1&taxa=Pasimachus&usethes=1&taxontype=1#

I tried searching for a group with fewer taxa to see if it was something related to the number of names printed and I found some weird results.

When searching for 'Trachypachus inermis' (a name not in our thesaurus for some reason, but we do have samples of these beetles) the map will return the name in the legend just fine:
<img width="1163" alt="Screen Shot 2022-03-01 at 12 46 28 PM" src="https://user-images.githubusercontent.com/6679254/156237917-33252558-4ad0-4c2a-8976-b7eac6211c1e.png">

I then tried to search for a genus in the middle, searching for 'Rhadine' where we have 3 species present in our occurrences and some just determined to genus.  This returned a map with the species names not printed to the legend but the genus name and "various taxa" printed: 
<img width="1150" alt="Screen Shot 2022-03-01 at 12 43 51 PM" src="https://user-images.githubusercontent.com/6679254/156238165-6aa6129f-8d51-4e39-a3ad-fcb4fb1afd23.png">

https://biorepo.neonscience.org/portal/collections/list.php?db=61%2C21%2C62%2C45%2C60%2C50%2C73%2C8%2C9%2C7%2C41%2C30%2C76%2C10%2C42%2C5%2C31%2C69%2C6%2C47%2C46%2C49%2C84%2C81%2C11%2C63%2C39%2C14%2C13%2C16%2C85%2C56%2C65%2C59%2C29%2C4%2C18%2C54%2C40%2C23%2C66%2C20%2C12%2C15%2C70%2C24%2C71%2C25%2C26%2C27%2C17%2C19%2C28&includeothercatnum=1&taxa=Rhadine&usethes=1&taxontype=1#

The desired functionality, of course, is for all names to be properly displayed.

Note: this is the standard occurrence search, view in map - the "map search" module seems to be working correctly.

**Comment by kyule** [comment]
Still an issue as of 4/18/22
