### ISSUE TITLE
Adjust harvester to fetch determination from different NEON's API `ingestTableName`

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#276]
This issue is related to multiple issues reported in the past that still seem to not have been fixed.

For an example from today, see: https://biorepo.neonscience.org/portal/collections/individual/index.php?occid=910694

The taxon code must have been pulled from the API, even though the taxon name is provided on the manifest.  This is very problematic.

First of all, we check in samples based on the manifest and those are the identifications that should be shown in the portal - API data should be secondary when it comes to determinations, or at the very least be added as a new determination event.

Second, in this case, these are expert IDs and the original parataxonomist ID metadata was pulled in from the API.

Parts of these issues have been reported before, but to my knowledge this is the first time that harvesting is overriding taxon names that are given in the manifest.

See also: https://github.com/BioKIC/NEON-Biorepository/issues/198
https://github.com/BioKIC/NEON-Biorepository-Data-Docs/issues/104
https://github.com/BioKIC/NEON-Biorepository-Data-Docs/issues/101
https://github.com/BioKIC/NEON-Biorepository-Data-Docs/issues/76
https://github.com/BioKIC/NEON-Biorepository-Data-Docs/issues/103
https://github.com/BioKIC/NEON-Biorepository-Data-Docs/issues/114
https://github.com/BioKIC/NEON-Biorepository-Data-Docs/issues/120

**Comment by mandrewj** [comment]
Bumping this issue - more incorrect IDs are being assigned to our occurrence records via harvesting.

See for instance: NEON.BET.D17.001828 which was identified as an undescribed species by the world authority, using the semi-unfortunate code "Pterostichus (Hypherpes) sp. TKW.2019.MorphC" as can be seen on https://biorepo.neonscience.org/portal/neon/shipment/manifestviewer.php?shipmentPK=2483

The occurrence harvester instead applied the taxon name from the API - which is not what the specimen is labeled as, not what it was checked-in as and not where it is curated in our collection.

This can futher be evidenced by NEON.BET.D19.000907 which we are now publishing using the parataxonomist ID 'Harpalus solitaris' https://biorepo.neonscience.org/portal/collections/individual/index.php?occid=915859 but the expert ID'd as 'Harpalus nigritarsis'

These errors are propogated throughout this and other similar manifests.

**Comment by arbolitoloco** [comment]
Moving Data Docs issue here, and continuing the conversation:

Hey @egbot:

For the particular linked occurrence mentioned,

> NEON.BET.D13.500984
> https://biorepo.neonscience.org/portal/collections/individual/index.php?occid=897473

the harvester is pulling the information from the `"ingestTableName": "bet_IDandpinning_in"`.

Harvested should be adjusted to pull the taxonomic determination from the `"ingestTableName": "bet_expertTaxonomistID_in"` instead.

**Comment by mandrewj** [comment]
CLosing - explained and covered in other issues
