### ISSUE TITLE
Implement citeme.txt files for downloads

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#287]
Finalize citeme.txt file format (conversation about possibilities is here: https://docs.google.com/document/d/1G0OnLJEL7LslIUHDdDpln3YCaVg54Se1cGiNKAI5Krg/) and make adjustments so that it is included in downloads.

**Comment by arbolitoloco** [comment]
Implemented by https://github.com/BioKIC/Symbiota/pull/261
