### ISSUE TITLE
Sample photos in Collections Descriptions Pages

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#30]
Add thumbnail photos of samples and specimens where useful to the collection description pages, e.g. photo of fluid-preserved bycatch specimens in invert bycatch collections' pages.

This will be largely on hold until we can return to the collections and take nice photos.

**Comment by kyule** [comment]
@arbolitoloco Ed agrees that adding them into the description field is the most practical and flexible solution.

**Comment by arbolitoloco** [comment]
## To Dos

- [x] Create spreadsheet with collections to capture collection managers' ideas on which collections to show images
- [x] Ask collection manager's to upload desired images in specific directory and add filename to columns per collection
- [ ] Download images
- [ ] Transform images (convert to small size; optimize for web)
- [ ] Add images to collection profiles
- [ ] Style images to be responsive

**Comment by kyule** [comment]
Completed!
