### ISSUE TITLE
Label Printing Issue: NEON Mammal (Skull Vial) Label is pulling in dynamicProperties and catNum for barcode

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#303]
The NEON Mammal (Skull Vial) Label profile is now displaying the dynamicProperties field in the label. This should be removed; the dynamicProperties field should not be visible on the label. Additionally, the barcode is displaying the catalogNumber instead of the sampleCode now. The barcode should use the sampleCode.

![image](https://user-images.githubusercontent.com/55719283/233453929-d5abc100-9176-487a-b161-ee06f3cae237.png)

Thanks in advance for fixing!

**Comment by arbolitoloco** [comment]
This was happening because one of the labels is missing the `recordedBy` information, so the JS file was throwing an error and wasn't being executed. I've fixed this issue, by adding a check for the presence of the `recordedBy` value in the label.
