### ISSUE TITLE
Enhancement request: add related occurrences to Mammal Collection (Vouchers [Standard Sampling]) (NEON-MAMC-VSS)

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#304]
Currently, all occurrence records for mammal blood, fecal, tissue, hair, etc. samples display related occurrence records for these samples. Would it be possible to also display related blood, tissue, fecal, hair, etc. samples within related voucher occurrence records? And vice versa?

Here is an example of how the related occurrences are being displayed for the blood, tissue, etc. Can we do this for the mammal vouchers that also have blood, tissue, fecal, etc,? And display the related voucher in the blood, tissue, fecal, hair, etc. records?

![image](https://user-images.githubusercontent.com/55719283/233467705-89c8bd10-0968-4b7b-a9f7-173791d4f1dc.png)

**Comment by kyule** [comment]
@lsteger This is something I could do in the backend. It wouldn't be programmatically applied for new vouchers, but I can do it periodically. If you create a sheet of the matching occids and the relationship (eg. derivedFromSameIndividual) between them, it will be easy for me!

**Comment by kyule** [comment]
Added all new (many thousands) relevant associationst o records of mammals samples from standard sampling, including VSS collection. This was based on matching tagIDs in the occurrence remarks field, so there could be missing ones or errors if tagID was not recorded. Did not include anything for the vouchers found outside of standard sampling. Can add more at any time, and also have open issue related to programmatically creating occurrence relationships: https://github.com/BioKIC/NEON-Biorepository/issues/331
