### ISSUE TITLE
Update needed to text on Collecting Event section of the sample search form

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#304]
The text under Collection End Date should read "Single date or **end** date of range." Also we should add text about the format the date should take "YYYY-MM-DD" or similar.

<img width="838" alt="image" src="https://user-images.githubusercontent.com/4763928/169913946-1e024cc3-3e59-4f61-b215-6358a5c03d40.png">

**Comment by arbolitoloco** [comment]
Closed by https://github.com/BioKIC/NEON-Biorepository/commit/d955b9290b1a0caa4a45d1131db30b88c66c6f12
