### ISSUE TITLE
Add Bionomia badges to collections

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#305]
Posting here for comment and issue tracking.

We would like to add Bionomia badges to collections. Bionomia tracks datasets via their GBIF dataset key, such as:
https://bionomia.net/dataset/f28219f3-49cd-4b55-99ad-39f3ced87ddd

When a collection is published to GBIF the citations badge gets activated within the Symbiota portal. I would request that the same also happen for the Bionomia badge - perhaps to appear right next to the citations badge on the collection profile.

One issue is that Bionomia updates its data from GBIF every 2 weeks so the dataset will not exist on the Bionomia website until after a bit of a lag. Not sure how to then choose to not display the badge until Bionomia has the collection?

We can also simply add the HTML code manually to each collection, but I think this would be a wonderful Symbiota-wide feature to add as well.

The suggested code is linked at the bottom of each dataset (just differs by dataset ID) and is:

`<a href="https://bionomia.net/dataset/f28219f3-49cd-4b55-99ad-39f3ced87ddd">
  <img src="https://api.bionomia.net/dataset/f28219f3-49cd-4b55-99ad-39f3ced87ddd/badge.svg" alt="Bionomia dataset badge" width="210" height="20">
</a>`

**Comment by mandrewj** [comment]
@egbot @arbolitoloco 
Added this little fix to the development branch if you find it acceptable:
https://github.com/BioKIC/NEON-Biorepository/commit/54dfc6b803d51d7e37853db0871b9f90c222c2c6

One issue is that if the dataset is not yet in Bionomia (max 2 week period from first GBIF publication date) then the badge will show this:

https://api.bionomia.net/dataset/BADDATASETKEY/badge.svg

**Comment by arbolitoloco** [comment]
Closed by PR #306

**Comment by dshorthouse** [comment]
Recent commits at Bionomia's end will properly catch the 404 HEAD requests at your end. Thanks for the commits @mandrewj & approval @egbot to make it better at my end. Hope this gets NEON participants thinking about the nature of their work & how they wish to be seen.

**Comment by mandrewj** [comment]
Thanks @dshorthouse ! I just realized a few days ago that an svg image is still produced with the 404 text in the image, such as this: https://api.bionomia.net/dataset/FAKE-GUID/badge.svg

We'll see how the new code on your end works and can adjust the Symbiota code if needed (perhaps doing a head request on the dataset page instead of on the image link).  Either way this is all a pretty minor issue since the badge is only displayed if the collection has a valid GBIF dataset key, so at most this is a 2 week issue per collection until Bionomia indexes it.

**Comment by dshorthouse** [comment]
Yep...bad behaviour on my end. There's a 404 http status alongside the human 404 image now so...with luck...your nice HEAD request via PHP curl will cease the unhelpful render.
