### ISSUE TITLE
Map search and collections search returning different results

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#31]
**Describe the bug**
Points displayed in map search are not the same as those displayed when you map samples  from collections search

**To Reproduce**
1. Go to search collections.
2. Select only Mammal Fecal collection
3. Enter USA in criteria.
4. Map
5. Go to map search.
6. Select only mammal fecal collection
7. Enter USA in criteria.
8. See that two maps do not show same samples.. for example all samples from site TREE are missing in map search. (note: downloading data from both does give same number of specimens) 

**Screenshots**
Collections search 
<img width="267" alt="image" src="https://user-images.githubusercontent.com/4763928/65171406-a3d45400-d9ff-11e9-9037-23d3ad5d0516.png">

Map search
<img width="347" alt="image" src="https://user-images.githubusercontent.com/4763928/65171428-afc01600-d9ff-11e9-8a8e-6ad4ea1b4d97.png">

**Desktop (please complete the following information):**
 - Browser: Firefox

**Comment by arbolitoloco** [comment]
I think this is related to #16, because I searched some sampleIds found in the Sample Search that aren't being retrieved in the Map Search, and it seems like the Map Search form is not tagging the appropriate selected collection.

**Comment by kyule** [comment]
Related to #16 and #58

**Comment by kyule** [comment]
Searches now resulting in correct results and matching between map and collections search.
