### ISSUE TITLE
Saved determination edits are not updated/saved under Latest Identification in the Occurrence Data tab

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#320]
When making edits to a determination (e.g. correcting a typo in the determination notes field and then saving those edits), nothing seems to update in the Latest Identification section of the Occurrence Data tab. Any updated and saved determination changes should transfer to the Latest Identification section in the Occurrence Data tab, but this doesn't seem to be happening.

**Comment by kyule** [comment]
Fixed by Ed during 12/23
