### ISSUE TITLE
Taxon Remarks field is not overwritten/cleared when a new determination is submitted

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#323]
When a new determination is submitted, the Taxon Remarks field is not overwritten (or cleared) and "Identification source: inferred from shipment manifest" continues to remain in that field and has to be manually erased. The Taxon Remarks field should be cleared when a new determination is submitted. See image below where a new determination was submitted but "Identification source: inferred from shipment manifest" remains in the Taxon Remarks field. 
![image](https://user-images.githubusercontent.com/55719283/229574904-98528880-96ac-4262-9b55-f563039b69e9.png)

**Comment by mandrewj** [comment]
For additional context, Issue was also listed here but marked as resolved pending a schema update, though is clearly still happening as noted in the issue above:

https://github.com/BioKIC/NEON-Biorepository/issues/51

**Comment by sunray1** [comment]
The fix to #363 should also fix this issue.
