### ISSUE TITLE
Soil taxonomy being overwritten with default value during reharvesting

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#327]
During reharvesting of samples the dry soils collection (https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=30) the soil taxa are being overwritten with the default taxon for the collection "Soil" during reharvesting. For example, see the edit history for this sample: https://biorepo.neonscience.org/portal/collections/individual/index.php?occid=238136

2022-03-31 12:34:38 --> harvester changed blank sciname to Histosoil
2022-09-27 11:53:20 --> harvester changed sciname Histosoil to Soil

**Comment by sunray1** [comment]
~~Make identifiedBy = recordedBy~~

See #427
