### ISSUE TITLE
Programmatically link occurrence relationships eg. DNA and voucher specimens

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#331]
Many DNA extracts are derived from vouchers where we also get that physical specimen voucher at the biorepository.

At least for the carabid beetles, most (and nearly all future) DNA extracts in https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=63 can be linked by having the same NEON sampleID as a pinned voucher in https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=39

These should all have 'associated occurence' relationships generated between the pairs using the relationship 'originatingSampleOf / subsampleOf' between them.

The mosquitoes should similar be done for collections https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=65 and https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=29

I believe this can and should also be done for DNA extractions of fish and maybe some mammals (though that might be more complex due to multiple tissue sample types)

**Comment by kyule** [comment]
Broken down and better outlined in some issues from 552 - 556 especially #554
