### ISSUE TITLE
Separation character for neonTheme

### ISSUE THREAD

**Issue by chrlaney** [BioKIC/NEON-Biorepository#340]
It would be great if 2 or more themes in the neonTheme field for the collection endpoint could be separated by a semi-colon. For example, in https://biorepo.neonscience.org/portal/api/v2/collection/68, the neonTheme is populated with "Biogeochemistry, Organisms, Populations, and Communities", and only looks like one theme. "Biogeochemistry; Organisms, Populations, and Communities" would be clearer. Thanks!

**Comment by kyule** [comment]
Agreed - Done.
