### ISSUE TITLE
Mammal wet label formatting issue

### ISSUE THREAD

**Issue by monotremata** [BioKIC/NEON-Biorepository#342]
When trying to generate wet labels for the following specimens, barcode and "Prep by." areas format incorrectly: NEON06SGC, NEON06SGD, NEON06SGE, NEON06SGF, NEON06SGG, NEON06SGH, NEON06SGI

**Comment by kyule** [comment]
@monotremata Can you check these again and see if this is improved? If not, can you provide screenshots of a good and a bad label for me to compare?

**Comment by monotremata** [comment]
They look good now! 

I forgot to attach a screenshot to this ticket, but they looked like this before:
![Screenshot 2023-11-20 092543](https://github.com/BioKIC/NEON-Biorepository/assets/101202504/97f20819-f38e-4de5-883d-7a44aa28bd4b)
And should look like this:
![Screenshot 2023-11-20 092533](https://github.com/BioKIC/NEON-Biorepository/assets/101202504/e126c6ac-a34c-4d9a-9b17-daff9546c9c5)

**Comment by monotremata** [comment]
The same formatting error happened with 3 of the labels I tried to generate today.

![Screenshot 2023-11-30 130349](https://github.com/BioKIC/NEON-Biorepository/assets/101202504/853c6d6d-0bf9-4c47-a45d-030e0803f08d)

**Comment by kyule** [comment]
Ok, I think these should work for you now. I've also diagnosed the overarching issue. The whole format breaks down when the recordedBy / collector field is not formatted exactly correctly. It has to be either just the name or name (ORCID XXXX- XXXX- XXXX- XXXX). For example, in one of these the last parantheses was left off and in another "ORCID" was left out. The harvester should be doing this correctly, some of these were input manually with typos.

**Comment by monotremata** [comment]
Thanks Kelsey! Good to know -  I was wondering what was causing it.
