### ISSUE TITLE
USA automatically populated in country field

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#35]
**Is your feature request related to a problem? Please describe.**
Users were confused why the Country field was included at all in the sample search criteria given the scope of the NEON program. Importantly this means that when searching for collections where all samples are undetermined, you have to put in locality criteria that don't make sense for NEON (e.g. site and domain are not searchable). This is especially problematic for collections which obviously do have some taxonomic restriction (e.g. plant foliar samples are plantae, microbial samples are microbial, bulk invertebrates are invertebrata) but we do not include anything beyond undetermined.

**Describe the solution you'd like**
USA automatically populated in the country field

**Comment by kyule** [comment]
May not be relevant depending on how @arbolitoloco's new search form is set up.

**Comment by arbolitoloco** [comment]
Closed by PR #217
