### ISSUE TITLE
Update NEON logo

### ISSUE THREAD

**Issue by chrlaney** [BioKIC/NEON-Biorepository#364]
The NEON logo being used at the top is only meant to be used for promotional items. It currently is the single-color logo, but it needs to be the most up-to-date lockup (attached). This is true of any logo used throughout the biorepo portal pages.
![NEON-NSF-2023-White (1)](https://github.com/BioKIC/NEON-Biorepository/assets/2153665/1c4041c3-249f-48a4-a9a7-56a1e96a94b8)
![NEON-NSF-2023 (2)](https://github.com/BioKIC/NEON-Biorepository/assets/2153665/22152f28-758b-47ac-9963-e4fc7633cabf)

**Comment by kyule** [comment]
@chrlaney  Do the little icon logos associated with the collections that get pulled onto the search results and record details pages need to be updated as well? Like this: 
<img width="102" alt="image" src="https://github.com/BioKIC/NEON-Biorepository/assets/4763928/b9946719-6582-4fb5-82fd-92494dbeedd1">

<img width="662" alt="image" src="https://github.com/BioKIC/NEON-Biorepository/assets/4763928/ad633d39-69e9-4452-8bf4-ebb99f6bda55">


And if so is there a good logo you can provide that works well as a small circle or square

**Comment by kyule** [comment]
I tried using the new logo for the collections specifically and the dimensions make it really small and overlapping with the headers: 
<img width="157" alt="image" src="https://github.com/BioKIC/NEON-Biorepository/assets/4763928/c7b1f73d-9b7d-4f7a-9b0e-26f475ed73c5">
<img width="467" alt="image" src="https://github.com/BioKIC/NEON-Biorepository/assets/4763928/502e9a80-4319-40bf-974c-2036e9dc722c">

**Comment by chrlaney** [comment]
Hi Kelsey, sorry, this is our only NSF-approved logo, so we'll have to make do. I think the little version with the title is okay, and then we'll just need a smaller version on the details tab as well.

**Comment by kyule** [comment]
Ok they are very small but they are there now. Replaced also in footer and header, thanks to much assistance from Ed.

**Comment by chrlaney** [comment]
Thanks @kyule !
