### ISSUE TITLE
Replace NSF logo in footer

### ISSUE THREAD

**Issue by chrlaney** [BioKIC/NEON-Biorepository#366]
![image](https://github.com/BioKIC/NEON-Biorepository/assets/2153665/7705dddc-e4ad-4ef4-a547-9b22f828140d)
See https://github.com/BioKIC/NEON-Biorepository/issues/364.
Thanks!

**Comment by mandrewj** [comment]
@kyule 
The new NEON/NSF footer logo is set to a relative size with no max constraint it seems. It overscales at least on pages with limited content:
<img width="2259" alt="Screenshot 2023-11-28 at 9 22 23 AM" src="https://github.com/BioKIC/NEON-Biorepository/assets/6679254/785c80be-eab0-4037-908d-15723e60831d">

**Comment by kyule** [comment]
Yep, known issue. I'm on it! Thanks for reporting.
