### ISSUE TITLE
TALL missing from D08 site list in search page

### ISSUE THREAD

**Issue by monotremata** [BioKIC/NEON-Biorepository#374]
![Screenshot 2023-12-13 113228](https://github.com/BioKIC/NEON-Biorepository/assets/101202504/98e7018c-e1a6-4954-9178-3e6d2e8c0df0)
Jonna noticed that TALL is not in the sites listed for D08 in the locality section of the search page.

**Comment by kyule** [comment]
@sunray1 Going to assign you here and in one other older issue, as a good first issues. This doesn't require deep understanding of the NEON data structure but will familiarize you with the code for  the neon sample search. I cannot find a reason why this would be happening based on the search form code or anything uniquely strange about the TALL entries in either omoccurdatasets or neon_field_sites tables. I have confirmed that no other site is missing from the form. It also needs to be fixed ahead of the TOS Palooza event in mid-January.

**Comment by sunray1** [comment]
Got it, thank you @kyule!!
