### ISSUE TITLE
Sample unable to receive IGSN

### ISSUE THREAD

**Issue by sunray1** [BioKIC/NEON-Biorepository#388]
There is one Invertebrate Bycatch sample that is marked as needing an IGSN, but is not recognized in the mapper, so does not receive an IGSN. 

![image](https://github.com/BioKIC/NEON-Biorepository/assets/21106063/faab7f2a-a8e1-4b05-b200-05cc302f2da2)

![image](https://github.com/BioKIC/NEON-Biorepository/assets/21106063/b172bb37-ffad-4f7e-9de7-5c78cb294a25)

**Comment by kyule** [comment]
Not sure why but I know longer see an issue sample for this collection
