### ISSUE TITLE
Collections descriptions pages images broken

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#393]
All image links are now broken across collections descriptions pages: E.g. https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=63

**Comment by sunray1** [comment]
Change links from "https://drive.google.com/uc?export=view&id=XXX" to "https://lh3.google.com/u/0/d/XXX"

**Comment by kyule** [comment]
Hmm. I tried that for the linked example collection and it still seems broken.

**Comment by sunray1** [comment]
I'll do it tomorrow - likely some html character cleaning going on or something that's changing the link for you.

**Comment by sunray1** [comment]
This is a bug on Google's end. Temporarily changed all google drive image links from ```https://drive.google.com/uc?export=view&id=XXX``` to ```https://drive.google.com/thumbnail?id=XXX&sz=w1000``` in https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php and https://biorepo.neonscience.org/portal/misc/staff.php.

Will have to keep an eye on https://issuetracker.google.com/issues/319531488.
