### ISSUE TITLE
Broken image links in taxon profile pages

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#397]
A small proportion of image links are broken within taxon profiles. For example, see: https://biorepo.neonscience.org/portal/taxa/index.php?taxon=45824
https://biorepo.neonscience.org/portal/taxa/index.php?taxon=86885

I'm seeing it in a few cases where the image is coming from SCAN or SEINet. I'm not sure whether it is related to the recent google issue.

**Comment by sunray1** [comment]
BisQue is down for maintenance today - hopefully those images come back tomorrow
Still need to inspect SCAN

**Comment by sunray1** [comment]
SEINet image links beginning with "bad" need to be updated (there are 28 records) - it looks like we can replace these with the correct images from SEINet
e.g. 
bad-https://storage.idigbio.org/portals/seinet/arizona/IND/IND-0066/IND-0066996_1491618180_web.jpg
to
https://swbiodiversity.org/imglib/storage/portals/seinet/midwest/IND/IND-0066/IND-0066996_1555653397_web.jpg

**Comment by sunray1** [comment]
SCAN images need to be checked and updated to the correct links if broken:
e.g., 
https://scan-bugs.org/imglib/scan/ASU_ASUHIC/ASUHIC0090/ASUHIC0090465_habitus_dorsal_1516911617.jpg
to
https://ecdysis.org/imglib/storage/portals/scan/ASU_ASUHIC/ASUHIC0090/ASUHIC0090465_habitus_dorsal_1516911617.jpg

**Comment by sunray1** [comment]
SEINet images are fixed

**Comment by sunray1** [comment]
SCAN images are fixed
