### ISSUE TITLE
Update external collections data

### ISSUE THREAD

**Issue by sunray1** [BioKIC/NEON-Biorepository#398]
There are two records I found when dealing with broken image links that have been deleted in SCAN - do these need to be deleted in NEON as well? Or maybe they need to be remapped?

https://biorepo.neonscience.org/portal/collections/individual/index.php?occid=223714
https://biorepo.neonscience.org/portal/collections/individual/index.php?occid=216453

**Comment by kyule** [comment]
@sunray1 I don't see a compelling reason not to delete them if they were deleted on SCAN (by Andrew!). On that thread, I would like to update our external collections data, SCAN, SEINet, CSVColl, potentially add Ecdysis at some point. Not urgent, but if it's something that sounds easy enough...

**Comment by sunray1** [comment]
Deleted. Leaving issue open for updating.
