### ISSUE TITLE
Delete determination history for microalgae collections

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#399]
Harvester, API, and legacy issues have caused major problems with taxonomy in the microalgae collections. As a stopgap to prevent confusion from messy and incorrect data (in part related to other open github issues related to harvester pulling from incorrect portions of the sample tree), especially during the AOS Palooza, we should delete all of the determination history associated with the 3 microalgae collections. collids= 46, 47, and 49. I will then input the correct ecological pseudotaxa for those samples.

**Comment by sunray1** [comment]
Would like some clarification on this one

**Comment by sunray1** [comment]
https://biorepo.neonscience.org/portal/collections/list.php?db=46

**Comment by sunray1** [comment]
Use NEON sampleID to get correct ID and determination. Delete all other determinations.
