### ISSUE TITLE
Taxon pages should have information about whether the taxon is found in NEON collections

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#40]
**Is your feature request related to a problem? Please describe.**
Users expect to see NEON specimens associated with a particular taxon when they go to the taxon page. 

**Describe the solution you'd like**
The interactive map icon could be placed higher / more prominent so they can see that some of this information is available. [Does become confusing when external collections are mapped there though]. Would it be possible to give the number of specimens associated linked to a list of them with each taxon (as is done when you browse through "more info.." on a given collection)?

eg, something like this 
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/4763928/65185082-ad6bb500-da1b-11e9-85d2-5a79225d5c2a.png">

when we are here: 

<img width="605" alt="image" src="https://user-images.githubusercontent.com/4763928/65185151-cd9b7400-da1b-11e9-81b0-49c9627a3216.png">

**Comment by kyule** [comment]
At meeting on 9/19/19, we also discussed something like icons or different colors for taxon names to indicate whether NEON specimens exist.

**Comment by arbolitoloco** [comment]
Closed by [PR #81 in Symbiota](https://github.com/BioKIC/Symbiota-light/pull/81)
