### ISSUE TITLE
Add collector names in plant voucher collection for collectors that only have ORCIDs listed

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#400]
I think we just need an updated list of collectors and their ORCIDS from NEON. 
![image](https://github.com/BioKIC/NEON-Biorepository/assets/55719283/91c5e64a-9d4c-4a50-a0b1-b8c2a878689c)

**Comment by kyule** [comment]
@lsteger We just got an updated one a couple weeks ago. That ORCID is in the table, so maybe try reharvesting? Or let me know what some of the occids are and I can look into it.

**Comment by kyule** [comment]
@lsteger reharvesting corrected this for one of the records with that collector: https://biorepo.neonscience.org/portal/collections/individual/index.php?occid=1085245

It will fix it for all records where the collector is now in the table and was not before. Let me know if you'd like me to reharvest the whole collection

**Comment by lsteger** [comment]
@kyule I reharvested the records and the collector name filled in for all except just a few with this ID: 0000-0002-9445-2841. Doesn't seem to be registered in ORCID though. Thanks for the pro tip about re-harvesting!

**Comment by kyule** [comment]
@lsteger My guess is that this is a typo and should be Marian Lea (ORCID 0000-0002-9445-2184). If you are comfortable with me manually updating these to reflect that, happy to do so.

**Comment by lsteger** [comment]
yes, please! thanks!

**Comment by kyule** [comment]
Done for both recordedBy and identifiedBy
