### ISSUE TITLE
Adjustment requested for the "NEON Herbarium Packet Label" label printing profile

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#421]
Currently, the ""NEON Herbarium Packet Label" profile for printing labels uses the NEON catalogNumber for the barcode instead of the sampleCode (barcode). See image below:

![image](https://github.com/BioKIC/NEON-Biorepository/assets/55719283/d5b7c17e-ed78-4445-89dd-5a3974397d36)

This seems to be happening when printing from the following collections:
Aquatic Plant, Bryophyte, and Macroalgae Collection (Herbarium Vouchers [Point Counts]) (NEON-APLC-HVPC)
Aquatic Plant, Bryophyte, and Macroalgae Collection (Herbarium Vouchers [Standard Sampling]) (NEON-APLC-HVSS)
Aquatic Plant, Bryophyte, and Macroalgae Collection (Herbarium Vouchers [Clip Harvests]) (NEON-APLC-HVCH)

As an example, try printing labels (NEON Herbarium Packet Label) for the following samples:
A00000297821,
A00000306033,
A00000297826,
B00000116162,
A00000297824,
A00000297808,
A00000297818,
A00000276937

**Comment by sunray1** [comment]
This is ultimately because these records are missing the family field.

Need to fix in code so this doesn't matter.
