### ISSUE TITLE
Mammal sexing data is being abbreviated

### ISSUE THREAD

**Issue by sunray1** [BioKIC/NEON-Biorepository#451]
In the mammal voucher data, the sex for some records is being overwritten/converted to F, M, or U instead of Male, Female, Unknown. This is happening to specimens that have already been prepared. Good news is that it doesn't look like it is overwriting changes that were made on the front end, but not 100% sure about this. Wondering if one of you could investigate why/when this is happening, perhaps reharvesting? Screen shot below, for example:

[Slack Message](https://neonbiorepository.slack.com/archives/CHP97HRNU/p1713974954517699?thread_ts=1713974954.517699&cid=CHP97HRNU)

**Comment by kyule** [comment]
Harvester does seem to have been the cause during a reharvest in Feb 24. Everything seems to be working correctly in that front end edits (either directly in the record or via skeletal file) are not being overwritten, as well as those made in the backend when I couple the updates with entries in the omocuredits table with myself as the user. I've done that for all instances where it was overwritten in the past. (Let me know if you run into an issue though) That does not prevent this from happening again to other records that hadn't been reharvested and then overwritten by the harvester. However, I will use this process to put in edits for ALL fields updated during the planned mammal data update process to be happening very soon and after _that_ the issue should not reoccur. Note however thought that unless a harvester code update is made any values will still come in as M,F,U as before for any records _except_ these.
