### ISSUE TITLE
Multiple identifications not included in GBIF downloads

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#454]
I was pretty certain that mulitple identificaitons were not included in the GBIF DwC downloads so I checked again. 

[See this collection ](https://www.gbif.org/dataset/1c99ecf5-672b-4af9-a532-8b28af9999bc)
Full download from our portal
[SymbOutput_2024-04-25_135912_DwC-A.zip](https://github.com/BioKIC/NEON-Biorepository/files/15121963/SymbOutput_2024-04-25_135912_DwC-A.zip)

Where a few specimens have multiple identifications, e.g. https://biorepo.neonscience.org/portal/collections/individual/index.php?occid=1009952&clid=0
That do come out in our DwC downloads. And are seen by GBIF: https://www.gbif.org/occurrence/4067911302

But no identifications file is present in the GBIF download: 

[0000397-240425142415019.zip](https://github.com/BioKIC/NEON-Biorepository/files/15121993/0000397-240425142415019.zip)

**Comment by sunray1** [comment]
Interesting, it's definitely supported - https://rs.gbif.org/extension/identification_history_2024-02-19.xml

I guess we're just not pushing?

**Comment by sunray1** [comment]
We are pushing these to GBIF - downloading the source archive shows the identification table:

[NEON-APLC-HVCH_DwC-A.zip](https://github.com/BioKIC/NEON-Biorepository/files/15297184/NEON-APLC-HVCH_DwC-A.zip)

**Comment by kyule** [comment]
Thanks, Chandra. Noting here that this confirms that (1) we are correctly publishing the identifications extension file; (2) the data are available on GBIF in individual records but are not downloadable from search results; (3) we posted on the GBIF forum to get input on whether that is an oversigth, planned development, etc.
