### ISSUE TITLE
Harvester indicating success when identifiers are incomplete in the API

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#473]
The harvester is now "successfully" harvesting samples when identifiers in the API are incomplete or incorrect relative to the manifest or current sample record. 

For example:
<img width="940" alt="image" src="https://github.com/BioKIC/NEON-Biorepository/assets/4763928/c44e470e-95fe-4ae8-ad73-3213765ecb7b">

A record was harvested for ARIK.20190327.CORE.1_DASYHELEA SP. when it should have failed due to a mismatch between the manifest (and physical sample) barcode and the barcode in the API.
<img width="1012" alt="image" src="https://github.com/BioKIC/NEON-Biorepository/assets/4763928/4e507bf0-33bc-4eb3-8e1b-20a9ae36a5eb">

(API value in the barcode is missing a 0).

<img width="846" alt="image" src="https://github.com/BioKIC/NEON-Biorepository/assets/4763928/f5009bb6-9267-451a-87fd-3d1204913ace">

Luckily, the errorMessage was not erased from the NeonSample table, but we do want instances in which there are mismatches in identifiers to altogether fail.

**Comment by sunray1** [comment]
I don't think the harvester ever checked for matching identifiers between barcode/sampleCode - see the checkIdentifiers function in OccurrenceHarvester.php.

I can add it though.

**Comment by kyule** [comment]
@sunray1 It does seem to be working correctly when the mismatch is in the uuid 
<img width="1017" alt="image" src="https://github.com/BioKIC/NEON-Biorepository/assets/4763928/e4f03429-3d6a-468f-b7e8-39bd50b91b00">

**Comment by sunray1** [comment]
Yup - it looks like it checks sampleUuid, sampleClass, IGSN and sampleId. But not barcode.

**Comment by kyule** [comment]
Hmmm. As of yesterday AM, these same samples were failing reharvest with the "NEON API failed to return sample data" errorMessage and the only issue I could see was the lack of match in the barcode.

**Comment by sunray1** [comment]
That's because of #469. Previously the code would try to search the API with the barcode, fail and return that error. Now it won't fail because it looks for data under the other identifiers too, but since there was never any error catching for the barcode, there was no failure returned.
