### ISSUE TITLE
Dynamic checklist returning taxa unrelated to search

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#49]
**Describe the bug**
Dynamic checklist search returns many taxa not related to the taxon filter

**To Reproduce**
1. Go to Dynamic Checklist.
2. "Oncorhynchus" in taxon filter
3. 1000 km radius
4. Drop pin somewhere in East Tennessee
5. Receive 579 taxa (plants, herps, etc --- one spp of Oncorhynchus was included)

Input: 
<img width="928" alt="image" src="https://user-images.githubusercontent.com/4763928/65202102-f2eda980-da3e-11e9-9c01-032eeedf94fa.png">

Result:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/4763928/65201920-d6517180-da3e-11e9-99a9-4d1a4510b480.png">
<img width="602" alt="image" src="https://user-images.githubusercontent.com/4763928/65202406-30523700-da3f-11e9-8b47-b941c91fd341.png">

**Desktop (please complete the following information):**
 - Firefox on mac

**Comment by arbolitoloco** [comment]
Could not reproduce behavior with steps above, assuming it's been fixed to some degree.
