### ISSUE TITLE
Images broken in collections descriptions pages

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#505]
All of the images of sample types in the collections profile description pages are broken. This may be the same issue as the staff profile pages? 

They should all be located here:

[](https://drive.google.com/drive/folders/1-fYYtAsSE-QJgOt4_fhCg0n1ON4fTGbk?usp=sharing)

**Comment by sunray1** [comment]
I see only a few of them are broken.

The ones that are broken I don't seem to have access to (i.e., https://drive.google.com/thumbnail?id=1mmXhmx4QTWZFWevTPk_NalNjPHP5xoC0&sz=w1000) - could they have potentially been under Laura's account?

**Comment by sunray1** [comment]
The issue is the images in folders outside of the typical folder had restricted permissions. :) Moved all outside images into the correct folder and updated permissions.
