### ISSUE TITLE
Inconsistencies in GBIF dataset publishing

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#506]
I just published the Domain Teaching Collection to GBIF. The collection does now exist there and looks exactly as I would expect: https://www.gbif.org/dataset/69e5ceb4-30a6-4074-8f9d-d6a0457cb789

It's even showing up in our publisher metrics: 
<img width="479" alt="image" src="https://github.com/user-attachments/assets/2efab9bf-1049-4f64-8d8f-20e7850cedaf">

However, it's not being counted in the total number of datasets 
<img width="784" alt="image" src="https://github.com/user-attachments/assets/0e9ac143-742c-4569-9f7c-c1a9504ab652">

Or listed in the datasets associated with us as a publisher: 

https://www.gbif.org/dataset/search?publishing_org=e794e60e-e558-4549-99f8-cfb241cdce24

It's definitely possible I'm forgetting a step in the publishing here, but in the past I've seen these updates happen really quickly. I think this is not the only collection for which this is happening, just based on the number of datasets I would expect (I think it should be more like 51), but I haven't dug into which others are missing.

**Comment by sunray1** [comment]
GBIF can take up to 24 hours to refresh sometimes, but will look into this

**Comment by kyule** [comment]
Thanks, _definitely_ ok to wait a couple days to see if it resolves. Just thought it was weird given prior experience and the total number seeming off even disregarding this newest one.

**Comment by sunray1** [comment]
FWIW - it does show up correctly in the registry (https://registry.gbif.org/installation/1de87984-ce7c-407c-988c-a28014ae53ad/servedDatasets and https://registry.gbif.org/organization/e794e60e-e558-4549-99f8-cfb241cdce24/publishedDataset). But I think you're right, something weird is going on with the front end.

**Comment by kyule** [comment]
As of the past 20 minutes (but not before!) they are there -  3 additional collections have just shown up, getting us to the expected number.
