### ISSUE TITLE
Make map option icons in checklists more prominent

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#51]
**Describe the bug**
Users liked the map options for the checklists but thought they were hidden.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/4763928/65203971-7b6d4980-da41-11e9-855b-ca388a9be510.png">

**Comment by arbolitoloco** [comment]
Ed has made some modifications to the checklist pages in Symbiota that changed the way the icons look
