### ISSUE TITLE
Merge plant voucher collections in front end search.

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#54]
**Is your feature request related to a problem? Please describe.**
These three collections should be combined. They are all plant vouchers, just collected while the techs were working on different protocols, like point counts.
Aquatic Plant Point Count Taxonomy Collection(NEON-APPCTC)    
Aquatic Plant Taxonomy Collection(NEON-APTC)    
Aquatic Plant Voucher Collection(NEON-APVC)
Also, we will have terrestrial plant vouchers as well and I think the aquatic and terrestrial should all be together in one Plant Voucher Collection (NEON-PVC).

**Describe the solution you'd like**
Merge these collections in the front end search.

**Comment by kyule** [comment]
I think a nested strategy is better such that the details of these separate collections and their associated protocols can be maintained while simplifying the search.

**Comment by arbolitoloco** [comment]
It seems to me like this has been resolved as a result of the "new" search form.
