### ISSUE TITLE
new neon macroinvertebrate taxa 

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#545]
[TO_UPLOAD_taxonTableIngest_additions_20240830.txt](https://github.com/user-attachments/files/16875391/TO_UPLOAD_taxonTableIngest_additions_20240830.txt)
[TO_UPLOAD_taxonLocationIngest_additions_20240830.txt](https://github.com/user-attachments/files/16875392/TO_UPLOAD_taxonLocationIngest_additions_20240830.txt)
[TO_UPLOAD_taxonTableIngest_additions_20240722.txt](https://github.com/user-attachments/files/16875394/TO_UPLOAD_taxonTableIngest_additions_20240722.txt)
[TO_UPLOAD_taxonLocationIngest_additions_20240722.txt](https://github.com/user-attachments/files/16875395/TO_UPLOAD_taxonLocationIngest_additions_20240722.txt)

From Steph Parker via ServiceNow:

> There have been recent updates to the aquatic macroinvertebrate taxon table. Please see the attached files for new additions.

**Comment by sunray1** [comment]
I've added/checked the taxa in neon_taxonomy and in the internal taxon tables.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/cearl4/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/cearl4/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">


tid|taxonCode|scientificName|scientificNameCanonical
-- | -- | -- | --
150567 | ESTUNG | Estellacarus unguitarsus | Estellacarus unguitarsus
150566 | ESTSP2 | Estellacarus sp. | Estellacarus
150566 | ESTSPP2 | Estellacarus spp. | Estellacarus
109681 | PROSP65 | Protosialis sp. | Protosialis
109681 | PROSPP65 | Protosialis spp. | Protosialis



</body>

</html>



I'm not 100% sure how we're dealing with these types of taxon fuzzing though? @egbot
