### ISSUE TITLE
External collections links in full record details pages

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#566]
Full record details pages link to "SESAR Record" based on occurrenceID and the NEON sample explorer based on some NEON identifier / otherCatalogNumber.

That only works when those links exist and the identifiers are formatted in the same way that the biorepo does. The ideal scenario would be to customize the links by collection. A minimum solution would be to simply remove them for external collections to reduce confusion.

**Comment by kyule** [comment]
I corrected the "source record" links since I realized it just required changes to the omcollections table.

**Comment by sunray1** [comment]
Do we need to fix the sample explorer button too?

**Comment by kyule** [comment]
Nope - you can just change where the url goes in the omcollections table, so now for the Essig records it's "Source Record" and goes to their database:

https://biorepo.neonscience.org/portal/collections/individual/index.php?occid=327946

I think with #568 we should be good
