### ISSUE TITLE
"Advertise" the inclusion of external collections

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#57]
**Is your feature request related to a problem? Please describe.**

Much of the UX confusion came from the inclusion of external collections; however, the existence of these collections greatly extends the portal's potential research uses. Their inclusion makes the portal not only a tool to discover NEON sample availability but also one that allows users to see a fuller picture of the biodiversity at a NEON site.

**Describe the solution you'd like**
Advertise the external collections on the portal --- "integrating NEON samples with specimens from the same sites in other collections, allowing for research on biodiversity at NEON sites over a broader taxonomic and temporal extent" etc. etc. --- homepage, search collections page, potentially an about page.

**Comment by arbolitoloco** [comment]
To improve recognition of external collections by users when viewing the results, I've added the logo images from SEINet and SCAN in their collection profiles. One caveat is that the images are not sized correctly and don't match the same aesthetics offered by the NEON logo, but for now it's the best we have.
