### ISSUE TITLE
Combine legacy collections into one

### ISSUE THREAD

**Issue by sunray1** [BioKIC/NEON-Biorepository#585]
As long as they are easily searchable and it's easy to figure out how they were collected (associated protocol is obvious)

[Aquatic Macroinvertebrate Prototype and Legacy NEON Samples (NEON-OPAL-AM)](https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=84)
[Mameyes (D04 MAME) Belowground Plant Biomass (Megapit) (NEON-OPAL-MB)](https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=93)
[Prototype and Legacy NEON Samples (NEON-OPAL)](https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=81)
[OPAL Soil Microbe Collection (Bulk Subsamples) (NEON-OPAL-SOMC) (NEON-OPAL-SOMC)](https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=96)

**Comment by kyule** [comment]
Mameyes belowground biomass samples moved to belowground biomass collection and occurrenceRemarks added regarding their associated OPAL data.

Just did a bunch of data cleaning to the OPAL aquatic inverts that were a mess and integrated them with the other OPAL collection.

@sunray1 Can you just hide collid 96 like the other collections that are "not available"?

@sunray1 Should I also go ahead and delete the archive pooling mammal collection and do all of the omcollections updates necessary for merging with the trap sorting one?

**Comment by sunray1** [comment]
Yes and yes.

**Comment by sunray1** [comment]
See #596 and #597

**Comment by kyule** [comment]
Merged collections and updated omcollections tables, etc.
