### ISSUE TITLE
New macroinvertebrate taxa

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#600]
New taxa to add from Steph Parker (RITM0070427):

[TO_UPLOAD_taxonTableIngest_additions_20241014.txt](https://github.com/user-attachments/files/17416783/TO_UPLOAD_taxonTableIngest_additions_20241014.txt)

[TO_UPLOAD_taxonTableIngest_additions_20241008.txt](https://github.com/user-attachments/files/17416784/TO_UPLOAD_taxonTableIngest_additions_20241008.txt)

**Comment by sunray1** [comment]
Need to remove https://biorepo.neonscience.org/portal/collections/misc/collprofiles.php?collid=112. Will do this once we get access to the server again. - done
