### ISSUE TITLE
Text under checklists are too small on Collection Statistics page

### ISSUE THREAD

**Issue by Egariepy2416** [BioKIC/NEON-Biorepository#64]
Text is too small under checklists on the Collection Statistics page.

https://biorepo.neonscience.org/portal/collections/misc/collstats.php

**Desktop (please complete the following information):**
 - Chrome
 - Version 77

**Comment by arbolitoloco** [comment]
Font size was too small due to `base.css` body option overriding styles set in `main.css`.
