### ISSUE TITLE
Incorrect accepted taxa mapping

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#657]
Not sure how widespread this is of an issue, probably fairly rare, but I found an instance in which the tidaccepted is incorrectly matched, probably due to duplicated neon taxon codes across different taxon groups.

In this case it was: 

Macroinvertebrate _Kribiodorum perpulchrum_ (tid= 147484, taxonCode=KRIPER) is actually a synonymn of _Stelechomyia perpulchra_ (tid= 110207, taxonCode= STEPER). It has the accepted NEON taxon code of STEPER. In the taxstatus table its tidaccepted is actually matched to _Stenolophus peregrinus_  (tid= 79059), which also has the taxonCode of STEPER but is in the BEETLE taxon group.

I updated this one which corrects some bad determinations in the portal, but it could be more widespread and is definitely something to keep in mind when loading new taxa.

**Comment by sunray1** [comment]
SELECT 
    taxa.tid, 
    taxa.sciname, 
    taxa.kingdomName, 
    t2.sciname AS acceptedscinameinportal, 
    t2.kingdomName AS acceptedkingdomNameinportal,
    neon_taxonomy.taxonCode as acceptedTaxonCodeinportal,
    nt2.acceptedTaxonCode as acceptedTaxonCodeinNEON
FROM 
    symbneon2.taxa 
JOIN 
    taxstatus 
    ON taxa.tid = taxstatus.tid 
JOIN 
    taxa t2 
    ON t2.tid = taxstatus.tidaccepted
JOIN
	neon_taxonomy
    ON taxstatus.tidaccepted=neon_taxonomy.tid
JOIN
	neon_taxonomy nt2
    ON taxa.tid=nt2.tid
WHERE 
    taxa.kingdomName <> t2.kingdomName AND
    taxa.kingdomName <> "";

**Comment by sunray1** [comment]
^^ should give us all the tids where the kingdom and acceptedKingdom are different, along with the acceptedTaxonCode and what it is according to NEON. I imagine there is considerable overlap between Fungi/Chromista/Plantae, so I'll ignore those, but I'll double check the others.

**Comment by sunray1** [comment]
Fixed a handful (<20) of these by hand. Hopefully any new additions will be constrained by Kingdom, reducing the likelihood of this happening.
