### ISSUE TITLE
Front page organization

### ISSUE THREAD

**Issue by Egariepy2416** [BioKIC/NEON-Biorepository#68]
In speaking to other undergraduates who frequently use the biorepository, we have agreed that the front page can be more visually appealing if the page is made to be vertical rather than horizontal, so that when you open up the page it is easier to understand what you are looking at. The phrase "Discover and access sample-based data" reads as a tagline, but the font and placement makes it look like a title, but it does not give a lot of context for what the NEON biorepository is. The font should be smaller and off to the side rather than centered, and the different subcategories should be lined up vertically underneath it with the large image off to the side or underneath the text. The description of the image should be in smaller text and centered under the image and if possible, a visual key should be added. Again, this is just a general suggestion made by the undergraduate team that is not necessary but we think it might make the site more visually stimulating.

**Comment by arbolitoloco** [comment]
Thank you, Emmy, suggestions are welcomed and appreciated! We will be further discussing the front-page design in the near future.

**Comment by chrlaney** [comment]
@arbolitoloco We're getting some very good information from our UI/UX evaluation vendor. Will bring info and draft wireframes with me next week.
