### ISSUE TITLE
Front-page checklists icon points to only plant checklists

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#69]
**Describe the bug**
Front-page icon below the map graphics that says "Checklists" points only to the *plant* checklists, rather than a generic checklist landing page, which would likely be more appropriate.

**Comment by arbolitoloco** [comment]
This issue is present because the checklists originally **were** only plant checklists, hence the outdated link.

**Comment by kyule** [comment]
Yeah, I figured! Figured it was also a very easy thing to be missed so I should report it.

**Comment by arbolitoloco** [comment]
Closed by 94c43719874682f05b3a9f8887e183a43dd43062
