### ISSUE TITLE
Spacing between login menu and main page text not correct when using Safari

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#73]
**Describe the bug**
The 'Login Menu' in the upper right of the main section of the page (Login, My Profile, sitemap) is not spaced above the text of at least some websites when viewed using Safari.

I have noticed this issue on the collection search page, individual collection views, and collection management pages.

**To Reproduce**
1. Go to collection search page using Safari
2.  See error

**Full URL**
https://biorepo.neonscience.org/portal/collections/index.php?

**Screenshots**
View in Safari: (note - on other pages it breaks the lines as well, typically this is some header about a collection or the tool/search you are using)
<img width="1407" alt="Screen Shot 2019-10-01 at 9 32 06 AM" src="https://user-images.githubusercontent.com/6679254/65982360-054ce780-e430-11e9-90f0-27b4e2d2bb47.png">

Here is the view from Google Chrome: (note the line spacing between the menu and main text of the page)

<img width="1557" alt="Screen Shot 2019-10-01 at 9 34 41 AM" src="https://user-images.githubusercontent.com/6679254/65982388-1695f400-e430-11e9-8e69-0d64ca0ece26.png">

**Desktop (please complete the following information):**
 - Browser: Safari v13 vs Chrome v77
- Macbook pro

**Comment by arbolitoloco** [comment]
Closed for being a duplicate from #71
