### ISSUE TITLE
Determine workflow to make updates to occurrence records as requested by Batelle team

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#77]
Sometimes changes need to be made directly on the manifest. Other times changes or other value-added data have been added to the occurence record. 

When reharvested, the record should update/overwrite anything that has been changed in the manifest but not overwrite what has been changed in the occurence record.

If NEON tells us to change the sample tag and date, so we update the manifest in that way, reharvesting should overwrite sample tag and date. However, if we a new determination has been input into the occurrence record, reharvesting should not overwrite that change with the original NEON taxonID

**Comment by arbolitoloco** [comment]
I believe @mandrewj has developed a workflow to deal with these changes for now. It would be great if he could add it to our documentation.

**Comment by kyule** [comment]
Right, he is planning to write this up for how to work with the system as it is now.

In the future, we would ideally want it to work such that any updates to the manifest due to requests from Battelle would lead to updates to the occurrence records when the record is re-harvested but not overwrite any changes that have already been made by collections managers or outside researchers (e.g. a new determination or addition of value-added data).

**Comment by kyule** [comment]
Andrew did write documentation. We need to be able to track potential occurrence records updates based on reharvesting with new API synching procedures, but as far as this issue is concerned, we are good.
