### ISSUE TITLE
Inconsistent Homepage link for collections

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#79]
Via Laura S. from 11/5/19 meeting

Inconsistent Homepage (change to Related Information or similar) link within each collection (sometimes to biorepo portal and sometimes to the associated dataset in the data portal).

Via KY:
Link to associated data set in main neon data portal is not preferred as there is far from a 1:1 relationship there. 

Unclear if needs to be done before pushing collections to GBIF?

**Comment by arbolitoloco** [comment]
As discussed in the same meeting mentioned above:

The 'homepage link' name in the Collection Profile Metadata page is misleading. This is not related to GBIF publishing for now. The solution agreed is to change that name to something to be defined, such as 'More information' or 'Related information'. This way the URL pointed there can be anything necessary, be it the data product link in NEON's main portal or something else entirely.

**Comment by kyule** [comment]
Ok, that was not clear to me at the meeting. Is it the collection managers who should choose this homepage link and input it for each collection?

**Comment by arbolitoloco** [comment]
Closed by https://github.com/BioKIC/NEON-Biorepository/commit/0a477223f423609ccfedf7305776c9a921eacd02
