### ISSUE TITLE
Moderate to large DWCA downloads time out

### ISSUE THREAD

**Issue by mandrewj** [BioKIC/NEON-Biorepository#9]
When downloading results from a standard occurrence search that has a moderate to large number of records, the page times out. This has happened to me using a mac running Chrome and Safari.

**Working:** A modest sized download of ~68k records takes a long while to form, but the page doesn't time out for me, such as this search (just click download and save with standard options selected): https://biorepo.neonscience.org/portal/collections/list.php?db=61%2C21%2C62%2C45%2C60%2C50%2C73%2C9%2C7%2C8%2C41%2C30%2C76%2C10%2C42%2C5%2C31%2C69%2C6%2C47%2C46%2C49%2C84%2C81%2C11%2C63%2C39%2C14%2C13%2C16%2C85%2C56%2C65%2C59%2C29%2C4%2C75%2C18%2C54%2C40%2C23%2C66%2C20%2C12%2C15%2C70%2C24%2C71%2C25%2C26%2C27%2C17%2C19%2C28&includeothercatnum=1&taxa=Carabidae&usethes=1&taxontype=1

**NOT Working** A mdoerately large search of ~211k records will time out during darwin core archive formation: https://biorepo.neonscience.org/portal/collections/list.php?db=41%2C30%2C76%2C10%2C42%2C11%2C63%2C39%2C14%2C13%2C16%2C85%2C56%2C65%2C59%2C29%2C4%2C75%2C18%2C54%2C40%2C23%2C66%2C20%2C12%2C15%2C70%2C24%2C71%2C25%2C26%2C27%2C17%2C19%2C28&includeothercatnum=1&usethes=1&taxontype=1

Here is the download page processing my request:

<img width="899" alt="Screen Shot 2022-10-19 at 1 25 03 PM" src="https://user-images.githubusercontent.com/6679254/196797156-4149e133-7441-4c2a-a3c9-1dbf7b549a7e.png">

Here is the timeout error:

<img width="900" alt="Screen Shot 2022-10-19 at 1 26 37 PM" src="https://user-images.githubusercontent.com/6679254/196797185-fbc2d99d-b398-4232-8631-7a38497060ea.png">

Perhaps this has something to do with the php timeout settings on the server, or perhaps it has something to do with the neonscience.org domain routing?

Tagging @egbot @GregPost-ASU

**Comment by GregoryPost** [comment]
The issue was resolved by removing the cloudflare CDN from the domain DNS.
