### ISSUE TITLE
Reset Form button overlaps dividing line in search form

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#95]
**Describe the bug**
Super minor aesthetic issue: The "reset form" button overlaps the line dividing the Taxonomic and Locality Criteria sections of the search form. Note that this happens and looks awkward on Firefox but not Chrome or Safari. 

**Full URL**
https://biorepo.neonscience.org/portal/collections/harvestparams.php

**Screenshots**
Firefox (version 71, 64-bit):

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/4763928/72281033-e34e2e00-35f6-11ea-9764-71f327c28105.png">

Chrome/Safari (dividing line does not extend, so there is no awkward overlap):

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/4763928/72281086-fe20a280-35f6-11ea-92b6-f0120e774032.png">

**Comment by arbolitoloco** [comment]
Yeah, that is a known issue. Thanks for reporting nonetheless. It won't be fixed until I'm able to rehaul the entire search form.
